<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mail_spool"
 *
 * Auto generated by Extension Builder 2015-12-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Mail Spool',
    'description' => 'Integrates swiftmailer spool transport for TYPO3.',
    'category' => 'misc',
    'author' => 'Frank Berger',
    'author_email' => 'fberger@sudhaus7.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '8.7.0-9.99.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
